### ISSUE TITLE
Design a nice view for Sponsorship section

### ISSUE THREAD

**Issue by soniasingla** [EmbarkStudios/opensource-website#61]
The sponsorship icons for the different are nice but a bit too abstract, wonder if using colored icons there makes it easier to see which services it is and that it is linked to them - @repi 

Thoughts: @arirawr @lpil @XAMPPRocky 🤔

**Comment by lpil** [comment]
I think it would be difficult to use their brand colours as they are not designed to compliment each other, or with our branding. I don't think it would be appropriate to alter their branding with a different colour-scheme

One thing I think may be nicer is to show the logos / pictures of the projects and people we are sponsoring, rather than logos of the platforms. Could even have featured ones with a little blerb explaining why they are important to us as well, similar to how GitHub does.

![image](https://user-images.githubusercontent.com/6134406/101014720-378b3500-355e-11eb-91c7-fe04fe07a438.png)

A problem with using the sponsees' logos etc is that we may been to spend more time managing this, or if it was automated we'd have less control over the images on our website.

**Comment by soniasingla** [comment]
@arirawr it would be nice if you can throw some light here :)

**Comment by arirawr** [comment]
I'm with Louis that design-wise the colours would not look great.

I'm not a great designer, but having some kind of visual representation like Louis suggested would be nice, but that's a question of if we want yet another manually-updated thing on the site.

**Comment by repi** [comment]
Don't take my original comment too seriously either, current stuff is quite good and may not be a good quick fix improvement for it

**Comment by soniasingla** [comment]
Closing this for now :)
