### ISSUE TITLE
Website built with static site generator

### ISSUE THREAD

**Issue by lpil** [EmbarkStudios/opensource-website#87]
It would be good if the site was built using a static site generator so that we don't need to copy the same header, footer, etc to each page.

This would also open up the door to creating a dev blog here if desired in future.

It would also enable us to generate the project/tag pages statically.

**Comment by Nisatru** [comment]
Heya, is there already some progress on this one?
If not I am interested in tackling this with Nuxt.js as a static site generator since the website uses Vue.js
I think the work on this can also be combined with #22

**Comment by celialewis3** [comment]
Hi there Nisatru, thank you for your interest! A few things - our main goal for rewriting the website as a static site is to reduce complexity and increase accessibility. Since the majority of our engineers do not work primarily in frontend, we are looking for a tech stack that does not require a deep familiarity with web tech like Vue, Angular, React, etc. Something like Nuxt.js/Vue.js requires a steeper learning curve and more web packages/dependencies than static site generators like Zola or Pelican. 

For these reasons, any development towards rewriting the site would most likely need to be done using these simpler static generators (Zola, Pelican, Hugo). 

And yes - that issue could definitely be merged with this one / needs to be updated to reflect our new thinking. Thanks for pointing that out!

**Comment by Nisatru** [comment]
That's a fair point

As a short free time project to expand my Vue.js knowledge with Nuxt.js I have done a rework of the embark.dev site with Nuxt.js so I already know the HTML and CSS stuff pretty well :smile: 

I had a look at Zola today and it really seems to be simpler than a static site generator using a SPA framework like Vue.js even though I have to get used to it since I usually work with SPA frameworks in the frontend so I might need some start time to rethink how its done in a static site generator like Zola :)

Do you have any preferences which of the static site generators (Zola, Pelican, Hugo) should be used?

**Comment by repi** [comment]
Have a general preference towards Zola because it is built in Rust, which our team uses heavily. Though don't have much experience with the different ones.

So that would likely be the primary one we would want to investigate. The feature matrix for it (on their own site) does look promising as well.

**Comment by Nisatru** [comment]
Yeah I had the same tendency from my short check of the given possibilities.
Will start to experiment with Zola then in the next days
